services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - micro-net

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - micro-net

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge